### ISSUE TITLE
No rule to make target 'libcryptominisat5'

### ISSUE THREAD

**Issue by MikolasJanota** [ltentrup/quabs#2]
std err
CMake Warning at CMakeLists.txt:716 (message):
  Testing is disabled

make[3]: *** No rule to make target 'libcryptominisat5'.  Stop.
make[2]: *** [libsolve/src/cmsat-prefix/src/cmsat-stamp/cmsat-build] Error 2
make[1]: *** [libsolve/src/CMakeFiles/cmsat.dir/all] Error 2
make: *** [all] Error 2

std out
[ 22%] Built target quabs-base
[ 24%] Built target solve
[ 27%] Built target qcir2qdimacs
[ 29%] Built target qaiger2qcir
[ 31%] Skipping update step for 'cmsat'
[ 32%] Performing configure step for 'cmsat'
-- LIB directory is 'lib'
-- BIN directory is 'bin'
-- Doing a RelWithDebInfo build
-- build type is RelWithDebInfo
-- Performing Test HAVE_FLAG_-mtune=native
-- Performing Test HAVE_FLAG_-mtune=native - Success
-- Compiling for static library use
-- GIT hash found: b6e9914ece2e9575c39e19ec90b8388118c3a0ee
-- PROJECT_VERSION: 5.6.8
-- PROJECT_VERSION_MAJOR: 5
-- PROJECT_VERSION_MINOR: 6
-- PROJECT_VERSION_PATCH: 8
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   program_options
-- Not compiling detailed statistics. The system is faster without them
-- Manpage will be created and installed
-- OK, Found ZLIB!
-- OK, Found M4RI lib at /usr/lib/x86_64-linux-gnu/libm4ri.a and includes at /usr/include
-- All defines at startup:  -DUSE_ZLIB -DUSE_M4RI
-- In case your Python interpreter is not found, or a wrong one is found, please set it with '-DPYTHON_EXECUTABLE:FILEPATH=your path here'
-- Python 3 -- PYTHON_EXECUTABLE=/usr/bin/python3
-- Python 3 -- PYTHON_LIBRARIES=/usr/lib/x86_64-linux-gnu/libpython3.6m.a
-- Python 3 -- PYTHON_INCLUDE_DIRS=/usr/include/python3.6m
-- Python 3 -- PYTHONLIBS_VERSION_STRING=3.6.7
-- Boost -- found at library: /usr/lib/x86_64-linux-gnu/libboost_program_options.a
-- Boost -- adding '/usr/lib/x86_64-linux-gnu' to link directories
-- Performing Test HAVE_FLAG_-Wformat=2
-- Performing Test HAVE_FLAG_-Wformat=2 - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mikolas/git/quabs/build/libsolve/src/cmsat-prefix/src/cmsat-build
[ 33%] Performing build step for 'cmsat'
libsolve/src/CMakeFiles/cmsat.dir/build.make:105: recipe for target 'libsolve/src/cmsat-prefix/src/cmsat-stamp/cmsat-build' failed
CMakeFiles/Makefile2:370: recipe for target 'libsolve/src/CMakeFiles/cmsat.dir/all' failed
Makefile:83: recipe for target 'all' failed

**Comment by ltentrup** [comment]
The build problem should be fixed with 9e9238d
Thanks for reporting!
